# Generated by Django 2.0 on 2018-03-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='appname',
            field=models.CharField(default='', max_length=32),
        ),
    ]
