# Generated by Django 2.0 on 2018-03-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0007_auto_20180302_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
