# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictrue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('origin_url', models.CharField(max_length=200)),
                ('local_path', models.CharField(max_length=200)),
                ('category_match', models.TextField()),
                ('picview', models.IntegerField()),
                ('order', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('create_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='PictrueTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_id', models.IntegerField()),
                ('tag_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('create_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
