# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sexypic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictrue',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pictrue',
            name='picview',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pictruetag',
            name='pic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sexypic.Pictrue'),
        ),
        migrations.AlterField(
            model_name='pictruetag',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sexypic.Tag'),
        ),
    ]
