# Generated by Django 2.0 on 2017-12-07 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sexypic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='owner',
        ),
    ]
