# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sexypic', '0002_auto_20171119_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictruetag',
            old_name='pic_id',
            new_name='pictrue',
        ),
        migrations.RenameField(
            model_name='pictruetag',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
