# Generated by Django 2.0 on 2017-12-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sexypic', '0003_snippet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='pictures',
            field=models.ManyToManyField(to='sexypic.Picture'),
        ),
    ]
