# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-22 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sexypic', '0003_auto_20171119_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('category_match', models.TextField()),
                ('picview', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('create_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumPictrue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sexypic.Album')),
                ('pictrue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sexypic.Pictrue')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sexypic.Album')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sexypic.Tag')),
            ],
        ),
    ]
