# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sexypic', '0004_album_albumpictrue_albumtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='category_match',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='pictrue',
            old_name='category_match',
            new_name='tags',
        ),
    ]
