# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sexypic', '0008_auto_20171122_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictrue',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
