# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sexypic', '0011_auto_20171122_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pictrue',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tag',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
