# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sexypic', '0012_auto_20171122_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictrue',
            name='qiniu_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
