# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sexypic', '0013_pictrue_qiniu_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pictrue',
            new_name='Picture',
        ),
    ]
