# Generated by Django 2.0 on 2017-12-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='bbsname',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
    ]
