# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20171204_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
