# Generated by Django 2.0 on 2017-12-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20171204_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='union_id',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=False, max_length=32, unique=True, verbose_name='板块名称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default=False, max_length=32, unique=True),
        ),
    ]
