# Generated by Django 2.0 on 2017-12-09 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_auto_20171207_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-publish_date',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('date',)},
        ),
    ]
