# Generated by Django 2.0 on 2018-03-02 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='文章标题')),
                ('content', models.TextField(default='内容')),
                ('publish_date', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('hidden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('priority', models.IntegerField(default=1000, verbose_name='优先级')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'ordering': ('-publish_date',),
            },
        ),
    ]
