# Generated by Django 2.0 on 2018-03-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreport', '0002_auto_20180302_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='author',
        ),
    ]
